
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    access-key-id: LTAI5tHqWbszib6LRbSeMh8p
    access-key-secret: ZjLbsXsGXea72M6tz5X1XPQ3Jj4M0U
    bucket-name: super-jar-xuke
  redis:
    host: 192.168.137.129
    port: 6379
    password: root
    database: 10
  wechat:
    appid: wx3dc682be747f175b
    secret: ZjLbsXsGXea72M6tz5X1XPQ3Jj4M0U